### ISSUE TITLE
typo in topic tag

### ISSUE THREAD

**Issue by Conal-Tuohy** [nationalarchives/kettle-jena-plugins#1]
The repo is currently tagged `penaho-spoon`

**Comment by adamretter** [comment]
@Conal-Tuohy I think this is fixed now. Do you still see an issue?

**Comment by Conal-Tuohy** [comment]
It still says `penaho-spoon` ... shouldn't it be `pentaho-spoon`?

**Comment by adamretter** [comment]
This appears to be fixed. Running:
```
grep -r "penaho" .
```

Shows no matches.

**Comment by Conal-Tuohy** [comment]
I was referring to the tag on the github repo itself.

![penaho](https://user-images.githubusercontent.com/1264711/107904825-ac381200-6f98-11eb-9d69-012221fd2148.png)

**Comment by adamretter** [comment]
@Conal-Tuohy Ahhhhh ha! Thanks Conal that's clear and I have corrected it now.
