### ISSUE TITLE
Strings with quotes in are not escaped correctly

### ISSUE THREAD

**Issue by adamretter** [nationalarchives/kettle-jena-plugins#18]
Given an input text of `"Africa" OR "Afrika"` we find that when serialized as an RDF literal value, we end up with missing escaped quotes at the beginning and end of the string. For example, the following Turtle is serialized:

```turtle
<http://www.nationalarchives.gov.uk/topic.2>
      a       skos:Concept ;
      dct:subject "Africa\" OR \"Afrika" ;
      skos:prefLabel "Africa" .
```

The `dct:subject` should instead look like:
```turtle
dct:subject "\"Africa\" OR \"Afrika\"" ;
```

**Comment by langsamu** [comment]
Couldn't reproduce. Works for me with grid or CSV input.
Can you point me at a transformation to fix or more specific example please.

**Comment by langsamu** [comment]
This is in the wrong repo.
Currect issue is nationalarchives/tna-cat#34.

**Comment by langsamu** [comment]
@adamretter please close.
