### ISSUE TITLE
Limited support for literal datatypes

### ISSUE THREAD

**Issue by langsamu** [nationalarchives/kettle-jena-plugins#2]
The _Jena Model Step_ supports only a limited set of datatypes that can be used to create literal objects.
Namely I wasn't able to create an `xsd:int`.

I think [`JenaModelStep.convertSqlValueToRdf`](https://github.com/nationalarchives/kettle-jena-plugins/blob/b34fa0d98698321df1ef3111e5478ca5e3b89250/src/main/java/uk/gov/nationalarchives/pdi/step/jena/model/JenaModelStep.java#L318) is where most of the work is needed to enhance datatype support:

https://github.com/nationalarchives/kettle-jena-plugins/blob/b34fa0d98698321df1ef3111e5478ca5e3b89250/src/main/java/uk/gov/nationalarchives/pdi/step/jena/model/JenaModelStep.java#L318-L352

**Comment by adamretter** [comment]
I would have hoped that was handled by:
```
} else if (sqlValue instanceof Number) { 
             return ((Number)sqlValue).toString(); 
```

What type of object is `sqlValue` when you choose `xsd:int` as the type?

**Comment by langsamu** [comment]
> I would have hoped that was handled by: `sqlValue instanceof Number`

[That](https://github.com/nationalarchives/kettle-jena-plugins/blob/b34fa0d98698321df1ef3111e5478ca5e3b89250/src/main/java/uk/gov/nationalarchives/pdi/step/jena/model/JenaModelStep.java#L330-L331) is only the case when the requested [datatype is a string (or none)](https://github.com/nationalarchives/kettle-jena-plugins/blob/b34fa0d98698321df1ef3111e5478ca5e3b89250/src/main/java/uk/gov/nationalarchives/pdi/step/jena/model/JenaModelStep.java#L319).

I'm talking about a case when the requested RDF literal's datatype is not known to `convertSqlValueToRdf` (for example `xsd:int`), and the input field value fits that value space:

![image](https://user-images.githubusercontent.com/240741/105221482-15229a80-5b51-11eb-9eaa-f27c804d1f88.png)

The specific point of failure is that `addResourceProperties` assumes the converted literal value is always a `String`

https://github.com/nationalarchives/kettle-jena-plugins/blob/b34fa0d98698321df1ef3111e5478ca5e3b89250/src/main/java/uk/gov/nationalarchives/pdi/step/jena/model/JenaModelStep.java#L300

even though `convertSqlValueToRdf` returns the raw `sqlValue` (a `long` in my example) on the _fallback_ branch:

https://github.com/nationalarchives/kettle-jena-plugins/blob/b34fa0d98698321df1ef3111e5478ca5e3b89250/src/main/java/uk/gov/nationalarchives/pdi/step/jena/model/JenaModelStep.java#L349-L351
