### ISSUE TITLE
Type triple is always created

### ISSUE THREAD

**Issue by langsamu** [nationalarchives/kettle-jena-plugins#3]
The _Jena Model Step_ always creates a type triple  for the constructed resource.

When the _Resource rdf:type_ input field is empty, the subject of the triple is the base URI:
```ttl
ex:resource1 a <> .
```

This is because `JenaModelStep.createModel` [always adds it](https://github.com/nationalarchives/kettle-jena-plugins/blob/b34fa0d98698321df1ef3111e5478ca5e3b89250/src/main/java/uk/gov/nationalarchives/pdi/step/jena/model/JenaModelStep.java#L168):

https://github.com/nationalarchives/kettle-jena-plugins/blob/b34fa0d98698321df1ef3111e5478ca5e3b89250/src/main/java/uk/gov/nationalarchives/pdi/step/jena/model/JenaModelStep.java#L160-L168

I think the assumption that a resource is necessarily typed doesn't always hold.
The related assumption that a resource has a single type doesn't either.

**Comment by adamretter** [comment]
Thanks @langsamu please can you give a concrete example of where you might want to create an untyped resource? It would help to show the RDF you expect for your use-case.

**Comment by langsamu** [comment]
I can imagine several situations where a type triple is not required:
1. User doesn't care about the type of the resource.
2. User doesn't know the type of the resource at the time of creating it in Kettle.
3. User is creating an RDF Collection (where type is usually not stated).
4. User relies on usage based classification, where types are not stated but inferred.
5. User needs multiple type statements (covered by #4).
