### ISSUE TITLE
No support for language-tagged strings

### ISSUE THREAD

**Issue by langsamu** [nationalarchives/kettle-jena-plugins#7]
The _Jena Model Step_ doesn't support creating language-typed literals in the _Fields to RDF Properties_ list.
Adding a _Language_ column to this list (and code that handles it) might be sufficient.

**Comment by adamretter** [comment]
Thanks @langsamu this would be a good feature to add. So far we didn't have a need for it, as all of our records data that I have seen so far is in English.
